# Change these first
owner: momentum-mod # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
skipTopicsUpdate: true

sites:
  - name: API
    url: https://api.momentum-mod.org/api-docs/
    icon: https://momentum-mod.org/favicon.ico
  - name: Main Site
    url: https://momentum-mod.org
  - name: Docs Site
    url: https://docs.momentum-mod.org
  - name: Blog Site
    url: https://blog.momentum-mod.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.momentum-mod.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/momentum-mod/status/master/assets/1000_nobg.png
  name: Momentum Mod Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://momentum-mod.org
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
