owner: momentum-mod
repo: status
skipTopicsUpdate: true

sites:
  - name: API
    url: https://api.momentum-mod.org/api-docs/
    icon: https://momentum-mod.org/favicon.ico
  - name: Main Site
    url: https://momentum-mod.org
  - name: Docs Site
    url: https://docs.momentum-mod.org
  - name: Blog Site
    url: https://blog.momentum-mod.org

status-website:
  cname: status.momentum-mod.org
  logoUrl: https://raw.githubusercontent.com/momentum-mod/status/master/assets/1000_nobg.png
  favicon: https://momentum-mod.org/favicon.png
  name: Momentum Mod Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://momentum-mod.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
