owner: momentum-mod
repo: status
skipTopicsUpdate: true

sites:
  - name: Staging API
    url: https://staging-api.momentum-mod.org/health
    icon: https://momentum-mod.org/favicon.ico
    showAverageResponseTime: false
  - name: Main API
    url: https://api.momentum-mod.org/api-docs/
    icon: https://momentum-mod.org/favicon.ico
    showAverageResponseTime: false

status-website:
  cname: status.momentum-mod.org
  logoUrl: https://raw.githubusercontent.com/momentum-mod/status/master/assets/1000_nobg.png
  favicon: https://momentum-mod.org/assets/favicon.png
  name: Momentum Mod Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Main Site
      href: https://momentum-mod.org

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
